### ISSUE TITLE
You must be logged in to store, or run in localhost. (NO results)

### ISSUE THREAD

**Issue by KostasBitsakos** [gioargyr/docker-kr-suite#2]
Hello,

I am using your container to run Strabon.
When I go to localhost:9999/Strabon I get nothing as result.
I get a 

You must be logged in to store, or run in localhost message.
But I cannot find nowhere a file to place creadentials for Strabon in your image.
Am I missing something?

**Comment by gioargyr** [comment]
Hello, Kostas. Follow instructions in README.md in "Using the docker-container".
fyi: The "Attention" note says it all.

**Comment by KostasBitsakos** [comment]
Hello, 

I am doing 
"Starting tomcat (terminal of container): rocket.sh
Attention When the container is up and running, it provides only a postgres(+postgis) DBMS. In order to make Strabon and Sextant available, you should start container's tomcat as described in the previous instruction.", as described.

But then again it asks me to log in if I want to make an update for instance.
I am using the tomcat credentials in the tomcat/conf/tomcat-users.xml, 
I also try the credentials in /tomcat/webapps/Strabon/WEB-INF/credentials.properties,
but nont of them seems to work.
It also asks me for postgresql credentials, where everything goes south.

**Comment by gioargyr** [comment]
Try
un: endpoint
pwd: 3ndp0int
