### ISSUE TITLE
Can't build docker-image from source.

### ISSUE THREAD

**Issue by selimsagir** [gioargyr/docker-kr-suite#3]
after clone your file to my local i can't understand which file i should run.

**Comment by jvanulde** [comment]
@selimsagir did you run `[sudo] docker build -t docker-image-name .`?

**Comment by jvanulde** [comment]
I managed to build the container and deploy it but can't access the WEB Services tools (Sextant, Strabon, OnTop Spatial) on my machine's port 9999.

**Comment by gioargyr** [comment]
Enter the container you created
$ [sudo] docker exec -it docker-container-name /bin/bash
Start tomcat (terminal of container): 
$ rocket.sh

**Comment by selimsagir** [comment]
Hello gioargyr, it worked fine i connect your docker but after reboot the PC all i did have gone. I can not see  image name in "docker images" and so i cannot run your docker.

**Comment by gioargyr** [comment]
Solved.
