### ISSUE TITLE
Can't access Sextant or Strabon

### ISSUE THREAD

**Issue by jvanulde** [gioargyr/docker-kr-suite#4]
I managed to build and deploy the container. I then followed these instructions:

    Using the docker-container:
    
    Use (the command line of) the container (terminal of your machine): [sudo] docker exec -it 
    docker-container-name /bin/bash
    
    Starting tomcat (terminal of container): rocket.sh
    
    Attention When the container is up and running, it provides only a postgres(+postgis) DBMS. 
    
    In order to make Strabon and Sextant available, you should start container's tomcat as described in the previous instruction.

    Now all the WEB Services tools (Sextant, Strabon, OnTop Spatial) are available in your machine's port 9999.

Tomcat is running on port 9999 but I have not idea on how to get to Sextant or Strabon.

**Comment by gioargyr** [comment]
Sextant is available at localhost:9999/Sextant_v2.0, while Strabon is available at localhost:9999/Strabon

**Comment by jvanulde** [comment]
👍
